### ISSUE TITLE
Log Out is broken

### ISSUE THREAD

**Issue by RedDragonWebDesign** [RedDragonWebDesign/BlueThrust5#112]
Really weird. This was working for me then it stopped working for me today.

I tried a commit from two years ago to make sure it wasn't a recent change that broke it, still isn't working.

I tried turning off XDebug, still isn't working.

Maybe something weird is going on with writing to $_SESSION and $_COOKIE. See 0c5d173. I saw hints that one would get written to with the new username, then they'd both end up back at the old username.

I am all debugged out after 0c5d173 so I will just clear my cookies and come back to this another day.

Cookies from DevTools:
<img width="717" alt="image" src="https://github.com/RedDragonWebDesign/BlueThrust5/assets/43397938/455206ee-6f37-4213-8e27-03ed9afe33d9">

<img width="1251" alt="image" src="https://github.com/RedDragonWebDesign/BlueThrust5/assets/43397938/1c843521-e983-483f-b129-d3617dbdbddf">

**Comment by deepend-tildeclub** [comment]
hmm.. still working on the copy I installed just before I started submitting patches today.  
I start with a fresh master copy every time I go through to figure out issues.
