### ISSUE TITLE
email notifications

### ISSUE THREAD

**Issue by deepend-tildeclub** [RedDragonWebDesign/BlueThrust5#36]
Is 
members/include/emailnotifications.php  gone for a specific reason?   Was it just extra broken?   Or is the functionality somewhere else now?    Would really like functioning notifications.

**Comment by RedDragonWebDesign** [comment]
I'm not sure. I'm not familiar with this feature. I'll take a look.

- Email notifications right? Not browser popups?
- Can you provide a specific example/test case/workflow of what is supposed to happen? For example, something like "I disable a member, it is supposed to email commanders, but I do not receive an email"
- Is there or did there used to be somewhere in My Account where notifications could be configured? Turned on/off for certain ranks, turned on/off for certain actions, etc?

Thanks a lot. Looking forward to your feedback.

Note to self. Possibly related? https://github.com/bluethrust/clanscripts/commit/bf4b31f4c118de8f397b9a77f3552d1bd61705ee

**Comment by deepend-tildeclub** [comment]
The file is in the version you download from bluethrust.com.      I have pasted it at https://bhh.sh/5vt   
I don't know exactly how it works because it is broken. 

The error I get in browser when I go into my email notification preferences under my account is:

Fatal error: Uncaught Error: Class 'SelectBox' not found in /path/to/public_html/members/include/emailnotifications.php:47 Stack trace: #0 /path/to/public_html/members/console.php(152): require() #1 {main} thrown in /path/to/public_html/members/include/emailnotifications.php on line 47

I originally set my site up using the version available for download on bluethrust.com  but overwrote it with your version when I noticed you did some fixes.   Which is probably the only reason I still have the emailnotifications.php file :)

Thanks

**Comment by RedDragonWebDesign** [comment]
Alright, I got my head wrapped around this. The version on the bluethrust.com website has changes from 2015 and 2016 that are not checked into the original GitHub. The original GitHub's last changes are from 2014.

So, I need to find a tool that compares the differences, then try to merge the 2015/2016 changes into v5. I'll try to work on this soon.

Awesome that you're using v5. Feel free to drop a star if you want. And feel free to submit tickets for any other issues you find.

**Comment by RedDragonWebDesign** [comment]
Alright, there were a ton of differences between the two versions. Sadly, I decided to reset the project to the version on the BlueThrust.com website and start from scratch. I will begin porting over the best v5 changes, and go from there.

Good news. Notifications should be fixed now.

Give me some time to port over v5 changes. If you have any features that you liked in particular, let me know and I'll give that priority.

![2020-10-26_194253](https://user-images.githubusercontent.com/43397938/97253895-7c3ae800-17ca-11eb-8d69-f9471d25d639.png)
