### ISSUE TITLE
readme.md - replace old theme screenshots with destiny screenshots

### ISSUE THREAD

**Issue by RedDragonWebDesign** [RedDragonWebDesign/BlueThrust5#57]

**Comment by deepend-tildeclub** [comment]
I assume this can be closed?  since I updated the screenshots :)   Or we waiting for me to do the wiki ones as well?

**Comment by RedDragonWebDesign** [comment]
Yes, let's close this.

In the future if you file a PR, put the words "Fixes #57" somewhere in the post, and it will link the PR to the issue, and auto-close it when the PR is merged :)
