### ISSUE TITLE
forum advanced search is broken

### ISSUE THREAD

**Issue by RedDragonWebDesign** [RedDragonWebDesign/BlueThrust5#65]
v4 - takes 20 seconds to load, then displays no results and is missing the footer

v5 - good load time, but displays no results, displays the correct result count though.

Problem in v5 appears to be related to `LIMIT 0, 0`

**Comment by deepend-tildeclub** [comment]
Not sure if it is a result of fixing other errors.. my search appears to function.  Was there any specific type of advanced search that was causing it to not work?  Or just the whole form in general?

**Comment by RedDragonWebDesign** [comment]
Basic and advanced search are broken for me on PHP 8.1. My localhost has one category, one public board, and one topic.
