### ISSUE TITLE
Console is empty for non-admins

### ISSUE THREAD

**Issue by deepend-tildeclub** [RedDragonWebDesign/BlueThrust5#77]
When signed in to my account I get this error:  and don't get any account menu options..

Notice: Undefined variable: blnShowCategoryList in /home/xxxxxxxxx/public_html/xxxxxxxxx/members/index.php on line 255

I have been trying to figure it out.. I can get rid of the error by adding a array();  to define it.. but doesn't make my menu come back. 

Thanks

**Comment by deepend-tildeclub** [comment]
Guessing this project is effectively dead?   Will close my issue.

**Comment by RedDragonWebDesign** [comment]
Hey there. Thanks for submitting your issue. I'm busy with my day job and don't have time to work on this project at the moment. Sorry about that. I do plan to circle back to it in the future, so doesn't hurt to submit issues and leave them open.

**Comment by deepend-tildeclub** [comment]
Any chance you could point me in the right direction? :+1: 
in "My Account" it shows no options. except when using the admin account.   no other accounts get any privileges to anything and no matter what I set an account to they have zero options to do anything which makes the site completely broken.  I've been trying to months to figure out why but I'm no programmer at all.. especially php... I can only fumble along so well.
Thanks anyways. sorry to bother you again since you said your busy.   

This error I fixed by changing  members/index.php  line 255 from 
 if($blnShowCategoryList || true) {

to 
 if($blnShowCategoryList = true) {

but that didn't solve anything outside of getting rid  of that error.

**Comment by RedDragonWebDesign** [comment]
Unable to reproduce.

Is your database set up correctly? What version of the scripts are you using? What version of PHP are you using? What's the URL of the page throwing the error (you can [submit this privately](https://www.reddragonwebdesign.com/contact/) if you want). Can you include a screenshot?

![image](https://user-images.githubusercontent.com/43397938/154861482-483b420c-c158-4237-b476-720e511be11b.png)

**Comment by deepend-tildeclub** [comment]
Sent you a reply via your link.  Thanks :)

**Comment by RedDragonWebDesign** [comment]
I was able to reproduce with a non-admin account. After step debugging, I've narrowed the problem down to this area of the code. `$member->hasAccess($consoleObj)` is returning `false` for everything.

https://github.com/RedDragonWebDesign/BlueThrust5/blob/master/src/members/index.php#L78-L92

Perhaps a database issue, involving default values used by the installer. I will continue investigating.

**Comment by RedDragonWebDesign** [comment]
Alright, the bug is in the SQL caching system I created. You can set _global_setup.php `$SQL_CACHE_ENABLED = false;` until I come up with a fix.

**Comment by deepend-tildeclub** [comment]
That's great.  Thank you very much.     I'll keep look at your issues listed and see what I can figure out.. I'm no expert or anything but I can figure at least somethings out.

**Comment by RedDragonWebDesign** [comment]
Sure. Feel free to submit issues and PRs. They help motivate me to work on this since I know someone is actually using it :)

**Comment by RedDragonWebDesign** [comment]
All fixed now. This typo of mine in _functions.php was the cause of the bug:

![image](https://user-images.githubusercontent.com/43397938/155037924-76306cc5-91c1-4660-af26-cced7daa8501.png)
