### ISSUE TITLE
skin BlueGrid - debugger - unreadable white on white text

### ISSUE THREAD

**Issue by RedDragonWebDesign** [RedDragonWebDesign/BlueThrust5#80]
Need a css !important somewhere

![image](https://user-images.githubusercontent.com/43397938/154911744-609bcb2b-43a4-4a2c-83c2-aac196534afe.png)

**Comment by deepend-tildeclub** [comment]
this color is hard coded into the themes/sql-profiler.php
Line: 23. 
Id submit a pull request on this as well but not sure if changing that to black or something would affect any other themes or should be broken out into its own setting in the styles.css of the themes themselves :)

**Comment by deepend-tildeclub** [comment]
actually removing the background-color from the sql-profiler.php line 23 would just have it use the background the rest of the theme uses.
